In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("EDA_done_data.csv")
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Unnamed: 0,1,2,3,4,5,6,8,9,10,11
job_id,JOB018462,JOB110011,JOB073462,JOB051683,JOB099770,JOB080320,JOB019108,JOB088302,JOB049451,JOB095723
company_name,DriftLearn,AnchorBuzz Labs,KiteSphere,AetherNode Co,QuantumBuzz Technologies,SpireCloud,NimbusFlow,VantageChain Systems,PinnacleBlock,EchoVita Technologies
company_type,Mid-size,MNC,Unicorn,MNC,MNC,MNC,FAANG-tier,Startup,MNC,Startup
sector,Cloud/Infra,HealthTech,HealthTech,Social/AdTech,SaaS,Fintech,Crypto/Web3,AI/ML,E-commerce,AI/ML
company_size_employees,5882,186507,10930,42510,86535,369939,53256,380,91371,160
hq_country,USA,USA,Brazil,USA,UK,USA,UK,Brazil,Singapore,India
job_role,Mobile Engineer (iOS),QA Engineer,Research Scientist,Product Manager,Data Engineer,UI Designer,Product Designer,Product Designer,Mobile Engineer (Android),Platform Engineer
seniority_level,Mid,Lead,Entry,Senior,Intern,Entry,Mid,Intern,Entry,Mid
years_experience_min,1,7,1,6,1,0,1,0,1,2
years_experience_max,4,15,4,9,1,1,5,0,2,7
required_tech_stack,"C++, TypeScript, Python, Kotlin","Swift, C++, Kotlin, Python","dbt, Spark, Python, Snowflake, Airflow","Amplitude, Jira, SQL, Notion, Figma","Snowflake, Python","Sketch, Figma","Adobe XD, Sketch, Framer, Figma","Adobe XD, Sketch","Python, Go","AWS, GCP"
primary_programming_language,Python,Go,R,<bound method DataFrame.mode of date_po...,Scala,<bound method DataFrame.mode of date_po...,<bound method DataFrame.mode of date_po...,<bound method DataFrame.mode of date_po...,JavaScript,Go
work_mode,Remote,Hybrid,Onsite,Hybrid,Hybrid,Onsite,Remote,Onsite,Hybrid,Hybrid
visa_sponsorship_offered,No,Yes,No,No,No,Yes,Yes,No,Yes,No
job_location_country,USA,USA,Germany,India,UK,USA,UK,Brazil,Israel,India
job_location_city,<bound method DataFrame.mode of date_po...,San Francisco,Frankfurt,Pune,London,New York,<bound method DataFrame.mode of date_po...,Rio de Janeiro,Tel Aviv,Hyderabad
salary_currency,USD,USD,EUR,INR,GBP,USD,GBP,BRL,ILS,INR
posting_date,2025-05-11,2025-12-01,2020-11-21,2025-07-03,2025-08-08,2022-04-18,2022-04-05,2025-04-25,2021-02-12,2021-07-23
application_deadline,2025-06-29 00:00:00,2026-01-24 00:00:00,2020-12-09 00:00:00,2025-07-19 00:00:00,2025-09-09 00:00:00,2022-06-16 00:00:00,2022-04-21 00:00:00,2025-05-23 00:00:00,2021-03-02 00:00:00,<bound method DataFrame.mode of date_po...
date_position_filled,<bound method DataFrame.mode of date_po...,2026-02-08,2020-12-21,2025-09-15,2025-09-09,2022-06-09,2022-08-17,2025-05-05,2021-03-08,2021-08-09
position_status,Open,Filled,Filled,Filled,Filled,Filled,Filled,Filled,Filled,Filled
number_of_applicants,134.0,36.0,300.0,43.0,58.0,281.0,78.0,349.0,205.0,41.0
number_of_interview_rounds,2.0,4.0,1.0,3.0,2.0,1.0,4.0,3.0,3.0,3.0
offers_extended,1.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
offers_accepted,0.0,1.0,5.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0
salary_min_usd,105800.0,238800.0,96300.0,105800.0,33100.0,87400.0,114500.0,42500.0,72300.0,115800.0
salary_max_usd,128800.0,274700.0,104000.0,245400.0,38500.0,98100.0,139700.0,47600.0,84700.0,152400.0
layoff_within_12_months_flag,No,No,Yes,Yes,No,No,No,No,Yes,No

In [3]:
df.select_dtypes(include=['int','float']).columns

Index(['Unnamed: 0', 'company_size_employees', 'years_experience_min',
       'years_experience_max', 'number_of_applicants',
       'number_of_interview_rounds', 'offers_extended', 'offers_accepted',
       'salary_min_usd', 'salary_max_usd'],
      dtype='object')

In [4]:
df['salary_usd'] = (df['salary_min_usd']+df['salary_max_usd'])/2

In [5]:
obj_col = df.select_dtypes(include=["object"])
for col in obj_col:
    print(f"{col}  =>  {df[col].nunique()}")

job_id  =>  111598
company_name  =>  895
company_type  =>  5
sector  =>  24
hq_country  =>  13
job_role  =>  160
seniority_level  =>  6
required_tech_stack  =>  29042
primary_programming_language  =>  16
work_mode  =>  13
visa_sponsorship_offered  =>  2
job_location_country  =>  13
job_location_city  =>  42
salary_currency  =>  10
posting_date  =>  2638
application_deadline  =>  2844
date_position_filled  =>  2792
position_status  =>  4
layoff_within_12_months_flag  =>  2

In [6]:
df["posting_date"] = pd.to_datetime(df["posting_date"],errors='coerce')
df["application_deadline"] = pd.to_datetime(df["application_deadline"],errors='coerce')
df["date_position_filled"] = pd.to_datetime(df["date_position_filled"],errors='coerce')

C:\Users\kumar\AppData\Local\Temp\ipykernel_13352\2642770621.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["date_position_filled"] = pd.to_datetime(df["date_position_filled"],errors='coerce')

In [7]:
df[df["posting_date"] > df["application_deadline"]]

Empty DataFrame
Columns: [Unnamed: 0, job_id, company_name, company_type, sector, company_size_employees, hq_country, job_role, seniority_level, years_experience_min, years_experience_max, required_tech_stack, primary_programming_language, work_mode, visa_sponsorship_offered, job_location_country, job_location_city, salary_currency, posting_date, application_deadline, date_position_filled, position_status, number_of_applicants, number_of_interview_rounds, offers_extended, offers_accepted, salary_min_usd, salary_max_usd, layoff_within_12_months_flag, salary_usd]
Index: []

[0 rows x 30 columns]

In [8]:
df[df["date_position_filled"] > df["posting_date"]]

,Unnamed: 0,job_id,company_name,company_type,sector,company_size_employees,hq_country,job_role,seniority_level,years_experience_min,...,date_position_filled,position_status,number_of_applicants,number_of_interview_rounds,offers_extended,offers_accepted,salary_min_usd,salary_max_usd,layoff_within_12_months_flag,salary_usd
1,2,JOB110011,AnchorBuzz Labs,MNC,HealthTech,186507,USA,QA Engineer,Lead,7,...,2026-02-08,Filled,36.0,4.0,1.0,1.0,238800.0,274700.0,No,256750.0
2,3,JOB073462,KiteSphere,Unicorn,HealthTech,10930,Brazil,Research Scientist,Entry,1,...,2020-12-21,Filled,300.0,1.0,6.0,5.0,96300.0,104000.0,Yes,100150.0
3,4,JOB051683,AetherNode Co,MNC,Social/AdTech,42510,USA,Product Manager,Senior,6,...,2025-09-15,Filled,43.0,3.0,1.0,1.0,105800.0,245400.0,Yes,175600.0
4,5,JOB099770,QuantumBuzz Technologies,MNC,SaaS,86535,UK,Data Engineer,Intern,1,...,2025-09-09,Filled,58.0,2.0,1.0,1.0,33100.0,38500.0,No,35800.0
5,6,JOB080320,SpireCloud,MNC,Fintech,369939,USA,UI Designer,Entry,0,...,2022-06-09,Filled,281.0,1.0,1.0,3.0,87400.0,98100.0,No,92750.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111590,114992,JOB049316,AnchorBuzz Labs,MNC,HealthTech,213410,USA,DevOps Engineer,Senior,6,...,2020-02-26,Filled,60.0,4.0,1.0,1.0,105800.0,128800.0,No,117300.0
111591,114993,JOB032470,BeaconPixel,MNC,Cloud/Infra,73418,Germany,Technical Program Manager,Mid,2,...,2022-03-18,Filled,105.0,3.0,1.0,1.0,125400.0,155200.0,No,140300.0
111592,114994,JOB081854,CatalystHub Co,Unicorn,AI/ML,3636,Ireland,Data Scientist,Intern,0,...,2022-02-18,Filled,243.0,1.0,1.0,1.0,37800.0,42500.0,No,40150.0
111593,114995,JOB012896,EmberReach Technologies,FAANG-tier,HealthTech,57977,UK,Software Engineer,Lead,7,...,2025-12-21,Filled,45.0,6.0,1.0,1.0,215300.0,254300.0,Yes,234800.0
111597,114999,JOB006559,QuantumBuzz Technologies,MNC,SaaS,108163,UK,Backend Engineer,Mid,3,...,2021-02-16,Filled,48.0,4.0,1.0,1.0,120400.0,147000.0,No,133700.0

In [9]:
df["Application_active_days"] = (df['application_deadline'] - df["posting_date"]).dt.days

In [10]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Unnamed: 0,1,2,3,4,5,6,8,9,10,11
job_id,JOB018462,JOB110011,JOB073462,JOB051683,JOB099770,JOB080320,JOB019108,JOB088302,JOB049451,JOB095723
company_name,DriftLearn,AnchorBuzz Labs,KiteSphere,AetherNode Co,QuantumBuzz Technologies,SpireCloud,NimbusFlow,VantageChain Systems,PinnacleBlock,EchoVita Technologies
company_type,Mid-size,MNC,Unicorn,MNC,MNC,MNC,FAANG-tier,Startup,MNC,Startup
sector,Cloud/Infra,HealthTech,HealthTech,Social/AdTech,SaaS,Fintech,Crypto/Web3,AI/ML,E-commerce,AI/ML
company_size_employees,5882,186507,10930,42510,86535,369939,53256,380,91371,160
hq_country,USA,USA,Brazil,USA,UK,USA,UK,Brazil,Singapore,India
job_role,Mobile Engineer (iOS),QA Engineer,Research Scientist,Product Manager,Data Engineer,UI Designer,Product Designer,Product Designer,Mobile Engineer (Android),Platform Engineer
seniority_level,Mid,Lead,Entry,Senior,Intern,Entry,Mid,Intern,Entry,Mid
years_experience_min,1,7,1,6,1,0,1,0,1,2
years_experience_max,4,15,4,9,1,1,5,0,2,7
required_tech_stack,"C++, TypeScript, Python, Kotlin","Swift, C++, Kotlin, Python","dbt, Spark, Python, Snowflake, Airflow","Amplitude, Jira, SQL, Notion, Figma","Snowflake, Python","Sketch, Figma","Adobe XD, Sketch, Framer, Figma","Adobe XD, Sketch","Python, Go","AWS, GCP"
primary_programming_language,Python,Go,R,<bound method DataFrame.mode of date_po...,Scala,<bound method DataFrame.mode of date_po...,<bound method DataFrame.mode of date_po...,<bound method DataFrame.mode of date_po...,JavaScript,Go
work_mode,Remote,Hybrid,Onsite,Hybrid,Hybrid,Onsite,Remote,Onsite,Hybrid,Hybrid
visa_sponsorship_offered,No,Yes,No,No,No,Yes,Yes,No,Yes,No
job_location_country,USA,USA,Germany,India,UK,USA,UK,Brazil,Israel,India
job_location_city,<bound method DataFrame.mode of date_po...,San Francisco,Frankfurt,Pune,London,New York,<bound method DataFrame.mode of date_po...,Rio de Janeiro,Tel Aviv,Hyderabad
salary_currency,USD,USD,EUR,INR,GBP,USD,GBP,BRL,ILS,INR
posting_date,2025-05-11 00:00:00,2025-12-01 00:00:00,2020-11-21 00:00:00,2025-07-03 00:00:00,2025-08-08 00:00:00,2022-04-18 00:00:00,2022-04-05 00:00:00,2025-04-25 00:00:00,2021-02-12 00:00:00,2021-07-23 00:00:00
application_deadline,2025-06-29 00:00:00,2026-01-24 00:00:00,2020-12-09 00:00:00,2025-07-19 00:00:00,2025-09-09 00:00:00,2022-06-16 00:00:00,2022-04-21 00:00:00,2025-05-23 00:00:00,2021-03-02 00:00:00,NaT
date_position_filled,NaT,2026-02-08 00:00:00,2020-12-21 00:00:00,2025-09-15 00:00:00,2025-09-09 00:00:00,2022-06-09 00:00:00,2022-08-17 00:00:00,2025-05-05 00:00:00,2021-03-08 00:00:00,2021-08-09 00:00:00
position_status,Open,Filled,Filled,Filled,Filled,Filled,Filled,Filled,Filled,Filled
number_of_applicants,134.0,36.0,300.0,43.0,58.0,281.0,78.0,349.0,205.0,41.0
number_of_interview_rounds,2.0,4.0,1.0,3.0,2.0,1.0,4.0,3.0,3.0,3.0
offers_extended,1.0,1.0,6.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
offers_accepted,0.0,1.0,5.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0
salary_min_usd,105800.0,238800.0,96300.0,105800.0,33100.0,87400.0,114500.0,42500.0,72300.0,115800.0
salary_max_usd,128800.0,274700.0,104000.0,245400.0,38500.0,98100.0,139700.0,47600.0,84700.0,152400.0
layoff_within_12_months_flag,No,No,Yes,Yes,No,No,No,No,Yes,No
salary_usd,117300.0,256750.0,100150.0,175600.0,35800.0,92750.0,127100.0,45050.0,78500.0,134100.0
Application_active_days,49.0,54.0,18.0,16.0,32.0,59.0,16.0,28.0,18.0,NaN

In [11]:
df.isnull().sum()

Unnamed: 0                          0
job_id                              0
company_name                        0
company_type                        0
sector                              0
company_size_employees              0
hq_country                          0
job_role                            0
seniority_level                     0
years_experience_min                0
years_experience_max                0
required_tech_stack                 0
primary_programming_language        0
work_mode                           0
visa_sponsorship_offered            0
job_location_country                0
job_location_city                   0
salary_currency                     0
posting_date                        0
application_deadline            11076
date_position_filled            25021
position_status                     0
number_of_applicants                0
number_of_interview_rounds          0
offers_extended                     0
offers_accepted                     0
salary_min_usd                      0
salary_max_usd                      0
layoff_within_12_months_flag        0
salary_usd                          0
Application_active_days         11076
dtype: int64

In [12]:
df['Application_active_days'] = df['Application_active_days'].fillna(-1)

In [13]:
df.isnull().sum()

Unnamed: 0                          0
job_id                              0
company_name                        0
company_type                        0
sector                              0
company_size_employees              0
hq_country                          0
job_role                            0
seniority_level                     0
years_experience_min                0
years_experience_max                0
required_tech_stack                 0
primary_programming_language        0
work_mode                           0
visa_sponsorship_offered            0
job_location_country                0
job_location_city                   0
salary_currency                     0
posting_date                        0
application_deadline            11076
date_position_filled            25021
position_status                     0
number_of_applicants                0
number_of_interview_rounds          0
offers_extended                     0
offers_accepted                     0
salary_min_usd                      0
salary_max_usd                      0
layoff_within_12_months_flag        0
salary_usd                          0
Application_active_days             0
dtype: int64

In [14]:
df = df.drop(columns=['job_id','company_name','required_tech_stack','job_location_city','salary_min_usd','salary_max_usd','application_deadline','date_position_filled','posting_date'])

In [15]:
obj_col = df.select_dtypes(include=["object"])
for col in obj_col:
    print(f"{col}  =>  {df[col].unique()}")
    print(" ")

company_type  =>  ['Mid-size' 'MNC' 'Unicorn' 'FAANG-tier' 'Startup']

sector  =>  ['Cloud/Infra' 'HealthTech' 'Social/AdTech' 'SaaS' 'Fintech' 'Crypto/Web3'
 'AI/ML' 'E-commerce' 'EdTech' 'Logistics' 'Cybersecurity' 'Gaming'
 'cloud/infra' 'gaming' 'crypto/web3' 'ai/ml' 'saas' 'edtech' 'logistics'
 'social/adtech' 'cybersecurity' 'healthtech' 'e-commerce' 'fintech']

hq_country  =>  ['USA' 'Brazil' 'UK' 'Singapore' 'India' 'Germany' 'France' 'Netherlands'
 'Canada' 'Israel' 'UAE' 'Australia' 'Ireland']

job_role  =>  ['Mobile Engineer (iOS)' 'QA Engineer' 'Research Scientist'
 'Product Manager' 'Data Engineer' 'UI Designer' 'Product Designer'
 'Mobile Engineer (Android)' 'Platform Engineer' 'Full Stack Engineer'
 'Backend Engineer' 'Application Security Engineer' 'Software Engineer'
 'SOC Analyst' 'Machine Learning Engineer' 'DevOps Engineer'
 'Frontend Engineer' 'Data Analyst' 'Embedded Systems Engineer'
 'Product Owner' 'Infrastructure Engineer' 'Associate Product Manager'
 'Analytics Engineer' 'Data Scientist' 'Technical Program Manager'
 'UX Designer' 'Site Reliability Engineer' 'Security Engineer'
 'Penetration Tester' 'Cloud Engineer' 'INFRASTRUCTURE ENGINEER'
 'UX Researcher' 'technical program manager' ' Frontend Engineer'
 'Mobile Engineer (iOS) ' 'Full Stack Engineer '
 'SITE RELIABILITY ENGINEER' ' Analytics Engineer' 'devops engineer'
 'mobile engineer (ios)' 'DATA ENGINEER' 'APPLICATION SECURITY ENGINEER'
 'cloud engineer' ' Embedded Systems Engineer' 'infrastructure engineer'
 ' Product Owner' ' Application Security Engineer' 'Product Owner '
 'Embedded Systems Engineer ' 'PLATFORM ENGINEER'
 ' Technical Program Manager' 'Mobile Engineer (Android) '
 'Product Manager ' 'Software Engineer ' ' Mobile Engineer (iOS)'
 'frontend engineer' ' Data Engineer' 'product owner' ' UI Designer'
 'data scientist' 'UX Designer ' 'ui designer' 'platform engineer'
 'Research Scientist ' 'Data Engineer ' 'data engineer' 'backend engineer'
 ' Penetration Tester' 'QA Engineer ' 'software engineer' 'qa engineer'
 'Security Engineer ' 'embedded systems engineer' ' Product Designer'
 'SOC Analyst ' ' Data Scientist' ' UX Designer'
 'ASSOCIATE PRODUCT MANAGER' ' UX Researcher' 'DevOps Engineer '
 'FRONTEND ENGINEER' 'mobile engineer (android)' ' QA Engineer '
 'Cloud Engineer ' ' Infrastructure Engineer' 'site reliability engineer'
 'product designer' ' SOC Analyst' ' Full Stack Engineer' 'UX RESEARCHER'
 'Backend Engineer ' ' Security Engineer' 'SOFTWARE ENGINEER'
 'FULL STACK ENGINEER' 'Frontend Engineer ' 'EMBEDDED SYSTEMS ENGINEER'
 'associate product manager' 'Data Analyst ' 'research scientist'
 ' Mobile Engineer (Android)' ' QA Engineer' ' Product Manager'
 'Machine Learning Engineer ' 'ux designer' 'MOBILE ENGINEER (IOS)'
 'penetration tester' ' Cloud Engineer' 'data analyst'
 'analytics engineer' ' Research Scientist' 'machine learning engineer'
 'Analytics Engineer ' 'Associate Product Manager '
 ' Site Reliability Engineer' 'DATA ANALYST' ' Data Analyst'
 'UI Designer ' ' Backend Engineer' 'QA ENGINEER' 'product manager'
 'Site Reliability Engineer ' 'DEVOPS ENGINEER'
 'Technical Program Manager ' 'application security engineer'
 'CLOUD ENGINEER' 'DATA SCIENTIST' ' DevOps Engineer' ' Software Engineer'
 ' Platform Engineer' 'BACKEND ENGINEER' ' Machine Learning Engineer'
 'RESEARCH SCIENTIST' 'SOC ANALYST' 'PRODUCT DESIGNER' 'ux researcher'
 'MACHINE LEARNING ENGINEER' 'ANALYTICS ENGINEER' 'security engineer'
 'Data Scientist ' 'Application Security Engineer ' 'full stack engineer'
 'MOBILE ENGINEER (ANDROID)' 'Product Designer ' 'SECURITY ENGINEER'
 'PENETRATION TESTER' ' Associate Product Manager'
 'Infrastructure Engineer ' 'soc analyst' 'Penetration Tester '
 'UI DESIGNER' 'UX Researcher ' 'TECHNICAL PROGRAM MANAGER' 'UX DESIGNER'
 'PRODUCT OWNER' 'PRODUCT MANAGER' 'Platform Engineer '
 ' FRONTEND ENGINEER' ' Data Analyst ' ' Mobile Engineer (iOS) '
 ' DATA ENGINEER']

seniority_level  =>  ['Mid' 'Lead' 'Entry' 'Senior' 'Intern' 'Principal']

primary_programming_language  =>  ['Python' 'Go' 'R'
 '<bound method DataFrame.mode of        date_position_filled job_location_city primary_programming_language  \\\n0                2023-11-20            Munich                           Go   \n1                       NaN               NaN                       Python   \n2                2026-02-08     San Francisco                           Go   \n3                2020-12-21         Frankfurt                            R   \n4                2025-09-15              Pune                          NaN   \n...                     ...               ...                          ...   \n114995           2025-12-21         Cambridge                       Kotlin   \n114996                  NaN               NaN                            R   \n114997                  NaN          Waterloo                          SQL   \n114998                  NaN            Mumbai                          NaN   \n114999           2021-02-16         Amsterdam                         Java   \n\n       application_deadline  \n0       2023-11-12 00:00:00  \n1       2025-06-29 00:00:00  \n2       2026-01-24 00:00:00  \n3       2020-12-09 00:00:00  \n4       2025-07-19 00:00:00  \n...                     ...  \n114995  2025-11-14 00:00:00  \n114996                  NaN  \n114997  2024-02-09 00:00:00  \n114998  2024-09-04 00:00:00  \n114999  2021-01-02 00:00:00  \n\n[115000 rows x 4 columns]>'
 'Scala' 'JavaScript' 'TypeScript' 'C++' 'Kotlin' 'Bash' 'Java' 'SQL'
 'Swift' 'C' 'Unknown' 'TBD']

work_mode  =>  ['Remote' 'Hybrid' 'Onsite' 'HYBRID' 'In-office' 'hybrid' 'remote' 'WFH'
 'onsite' 'REMOTE' 'ONSITE' 'On-site' 'Work From Home']

visa_sponsorship_offered  =>  ['No' 'Yes']

job_location_country  =>  ['USA' 'Germany' 'India' 'UK' 'Brazil' 'Israel' 'Singapore' 'Netherlands'
 'Canada' 'UAE' 'France' 'Australia' 'Ireland']

salary_currency  =>  ['USD' 'EUR' 'INR' 'GBP' 'BRL' 'ILS' 'SGD' 'CAD' 'AED' 'AUD']

position_status  =>  ['Open' 'Filled' 'Cancelled' 'Withdrawn']

layoff_within_12_months_flag  =>  ['No' 'Yes']

In [16]:
def abc(str):
    str = str.strip()
    str = str.lower()
    return str

df['job_role'] = df['job_role'].apply(abc)
df['sector'] = df['sector'].apply(abc)
df['work_mode'] = df['work_mode'].apply(abc)

# df['job_role'].unique()

In [17]:
df['work_mode'] = df['work_mode'].replace({'wfh':'work from home', 'on-site':'onsite'})
df['work_mode'].unique()

array(['remote', 'hybrid', 'onsite', 'in-office', 'work from home'],
      dtype=object)

In [18]:
obj_col = df.select_dtypes(include=["object"])
for col in obj_col:
    print(f"{col}  =>  {df[col].nunique()}")

company_type  =>  5
sector  =>  12
hq_country  =>  13
job_role  =>  31
seniority_level  =>  6
primary_programming_language  =>  16
work_mode  =>  5
visa_sponsorship_offered  =>  2
job_location_country  =>  13
salary_currency  =>  10
position_status  =>  4
layoff_within_12_months_flag  =>  2

In [19]:
# One hot encoding
df = pd.get_dummies(df,columns=['company_type','sector','hq_country','seniority_level','work_mode','job_location_country','primary_programming_language','salary_currency','position_status','job_role'], dtype=int, drop_first=True)

In [20]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['No','Yes']], dtype=int)
df['visa_sponsorship_offered'] = oe.fit_transform(df[['visa_sponsorship_offered']])
df['layoff_within_12_months_flag'] = oe.fit_transform(df[['layoff_within_12_months_flag']])

In [21]:
df.head(10)

,Unnamed: 0,company_size_employees,years_experience_min,years_experience_max,visa_sponsorship_offered,number_of_applicants,number_of_interview_rounds,offers_extended,offers_accepted,layoff_within_12_months_flag,...,job_role_qa engineer,job_role_research scientist,job_role_security engineer,job_role_site reliability engineer,job_role_soc analyst,job_role_software engineer,job_role_technical program manager,job_role_ui designer,job_role_ux designer,job_role_ux researcher
0,1,5882,1,4,0,134.0,2.0,1.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,186507,7,15,1,36.0,4.0,1.0,1.0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,10930,1,4,0,300.0,1.0,6.0,5.0,1,...,0,1,0,0,0,0,0,0,0,0
3,4,42510,6,9,0,43.0,3.0,1.0,1.0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,86535,1,1,0,58.0,2.0,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,369939,0,1,1,281.0,1.0,1.0,3.0,0,...,0,0,0,0,0,0,0,1,0,0
6,8,53256,1,5,1,78.0,4.0,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
7,9,380,0,0,0,349.0,3.0,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
8,10,91371,1,2,1,205.0,3.0,1.0,1.0,1,...,0,0,0,0,0,0,0,0,0,0
9,11,160,2,7,0,41.0,3.0,1.0,1.0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df.to_csv("Feature_engineering_done.csv")